# Generated by Django 3.0.1 on 2019-12-28 16:34

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20191228_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='number_1',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='number_2',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='number_3',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='number_4',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='number_5',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='number_6',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='number_7',
        ),
        migrations.AddField(
            model_name='ticket',
            name='numbers_selected',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
